#!/usr/bin/env bash
# A bash script to install haproxy load balancer
# ...and configure 2 nginx web servers to it.
# Also Makes sure that HAproxy can be managed via an init script

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 64466-web-01 54.237.15.115 check port 3200\n\tserver 64466-web-02 100.26.172.246 check port 3201 backup\n' /etc/haproxy/haproxy.cfg
service haproxy restart
