#!/usr/bin/env bash
# A bash script to install haproxy load balancer
# ...and configure 2 nginx web servers to it.
# Also Makes sure that HAproxy can be managed via an init script

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 64466-web-01 34.229.254.249:80 check\n\tserver 64466-web-02 54.162.96.240:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
