#!/usr/bin/env bash
# A bash script that uses the 
#+ while loop and if statement

i=0
while [ $i -lt 10 ];
do
	if [ $i -eq 8 ];
	then
		echo 'Best School'
		echo 'Hi'
	else
		echo 'Best School'
	fi
	((i++))
done
