#!/usr/bin/env bash
# A bash script that loops from 1 to 10
# prints 'bad luck' at 4th iteration
# prints 'good luck' at 8th iteration
# using the while loop

i=1
while [ $i -le 10 ];
do
	if [ $i == 4 ]
	then
		echo 'bad luck'
	elif [ $i == 8 ]
	then
		echo 'good luck'
	else
		echo 'Best School'
	fi
	((i++))
done
