#!/usr/bin/env bash
# A bash script that prints numbers from 1 to 20
#+ With special outputs for certain iterations
#+ Using the while loop and case statement

i=1
while [ $i -le 20 ];
do
	case $i in
		4 )
			echo $i
			echo 'bad luck from China' ;;
		9 )
			echo $i
			echo 'bad luck from Japan' ;;
		17 )
			echo $i
			echo 'bad luck from Italy' ;; 
		* )
			echo $i ;;
	esac
	((i++))
done
