#!/usr/bin/env bash
# A script that prints a clock
#+ hours 0 to 12
#+ minutes from 1 to 59

i=0
while [ $i -le 12 ];
do 
	echo 'Hour:' $i
	j=1
	while [ $j -le 59 ];
	do
		echo $j
		((j++))
	done
	((i++))
done
